# Generated by Django 4.2.7 on 2024-03-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_teacher_assigned_batches_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='teacher',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.month'),
        ),
    ]
