# Generated by Django 4.2.7 on 2024-03-08 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_teacher_assigned_batches_remove_teacher_user_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='s_enrolled_batches',
            field=models.ManyToManyField(related_name='s_enrolled_batches', to='course.batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='s_fees',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='s_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='t_assigned_batches',
            field=models.ManyToManyField(blank=True, related_name='t_assigned_batches', to='course.batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='t_join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='t_salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='t_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_num',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
