# Generated by Django 4.2.7 on 2024-03-08 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
