# Generated by Django 4.2.7 on 2024-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_teacher_payment_user_alter_payment_batch_and_more'),
        ('authentication', '0007_alter_user_s_fees_alter_user_t_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s_enrolled_batches',
            field=models.ManyToManyField(blank=True, related_name='s_enrolled_batches', to='course.batch'),
        ),
    ]
